/*1*/int aqi_num(float value);
/*2*/int id_check(char id[100]);
/*3*/int time_check(char str[100]);
/*4*/int values_check(char str[100]);
/*5*/int aqi_check(char aqi[100]);
/*6*/void dec2hex (int decimalNumber, int bytes_num, char* hex_bytes_display);
/*7*/void float2bi (double realNumber, char* binary);
/*8*/void dec2bi (int decimalNumber, char* binary);
/*9*/void float2hex754(double realNumber, int bytes_num, char* hex_bytes_display);
/*10*/int hex2dec (char hex2[3]);
/*11*/int bi2dec (char bi[100]);
/*12*/void bi2twocomp2hex(char bi[100], char* result);
/*13*/void checksum (char hex_12[100], char* result);
/*14*/float afterdot_bi2float(char str[100]);
/*15*/float hex754_2float (char str[9]);
/*16*/int dat_line_check(char str[100]);
void swap_int(int *a, int*b);
void swap_float(float *a, float *b);
/*17*/void bubble_vt(int *id, int *time, float *values, int num, char *pri_queue, int sort_sign, int *result);
/*18*/void quick_loop(float *data, int num, int start, int stop, int *result);
/*19*/void quick_vt(int *id, int *time, float *values, int num, char *pri_queue, int sort_sign, int *result);
